In [1]:
#importar libreias requeridad
import pandas as pd 
import numpy
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
%pip install matplotlib
%pip install seaborn

Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (2.2.2)
Requirement already satisfied: packaging>=20.0 in /Users/jos/Library/Python/3.13/lib/python/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/jos/Library/Python/3.13/lib/python/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/jos/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (2.2.2)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Users/jos/Library/Python/3.13/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/jos/Library/Python/3.13/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/jos/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
#meter mi pais 
berlin_data= pd.read_csv("Berlin_Alemania.csv")
pd.options.display.max_rows = 10
pd.options.display.max_columns = 10
berlin_data.head()

,Unnamed: 0,id,scrape_id,name,description,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,2084992,20241221052002,"Nice and cozy apartment in Kreuzberg, Graefekiez",Our cosy two room Apartment (70qm) in a vibrat...,...,1,1,0,0,0.09
1,1,1123383729460847373,20241221052002,Furnished room in well equipped serviced apart...,Room in an apartment available. Apartment has ...,...,3,1,2,0,NaN
2,2,1205255838613758737,20241221052002,Luxurous game room with private bath in X-Berg,Cozy private room in Berlin Mitte with private...,...,1,0,1,0,9.53
3,3,8164759,20241221052002,Beautiful single-room studio,Experience the “real Berlin” in our small and ...,...,1,1,0,0,0.01
4,4,18836877,20241221052002,Unterkunft zentral in Berlin,"The accommodation has 3 rooms, however, is onl...",...,1,1,0,0,NaN

In [3]:
berlin_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13984 entries, 0 to 13983
Data columns (total 51 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Unnamed: 0                                    13984 non-null  int64
 1   id                                            13984 non-null  int64
 2   scrape_id                                     13984 non-null  int64
 3   name                                          13984 non-null  object
 4   description                                   13365 non-null  object
 5   host_id                                       13984 non-null  int64
 6   host_name                                     13975 non-null  object
 7   host_is_superhost                             13847 non-null  object
 8   host_listings_count                           13975 non-null  float64
 9   host_total_listings_count                     13975 non-null  float64
 10  host_has_profile_pic                          13975 non-null  object
 11  host_identity_verified                        13975 non-null  object
 12  latitude                                      13984 non-null  float64
 13  longitude                                     13984 non-null  float64
 14  property_type                                 13984 non-null  object
 15  room_type                                     13984 non-null  object
 16  accommodates                                  13984 non-null  int64
 17  bathrooms                                     9002 non-null   float64
 18  bedrooms                                      11924 non-null  float64
 19  beds                                          8971 non-null   float64
 20  price                                         8990 non-null   object
 21  maximum_nights                                13984 non-null  int64
 22  minimum_minimum_nights                        13984 non-null  int64
 23  maximum_minimum_nights                        13984 non-null  int64
 24  minimum_maximum_nights                        13984 non-null  int64
 25  maximum_maximum_nights                        13984 non-null  int64
 26  minimum_nights_avg_ntm                        13984 non-null  float64
 27  maximum_nights_avg_ntm                        13984 non-null  float64
 28  calendar_updated                              0 non-null      float64
 29  has_availability                              13140 non-null  object
 30  availability_30                               13984 non-null  int64
 31  availability_60                               13984 non-null  int64
 32  availability_90                               13984 non-null  int64
 33  availability_365                              13984 non-null  int64
 34  number_of_reviews                             13984 non-null  int64
 35  number_of_reviews_ltm                         13984 non-null  int64
 36  number_of_reviews_l30d                        13984 non-null  int64
 37  review_scores_rating                          10706 non-null  float64
 38  review_scores_accuracy                        10704 non-null  float64
 39  review_scores_cleanliness                     10706 non-null  float64
 40  review_scores_checkin                         10703 non-null  float64
 41  review_scores_communication                   10705 non-null  float64
 42  review_scores_location                        10703 non-null  float64
 43  review_scores_value                           10701 non-null  float64
 44  license                                       8827 non-null   object
 45  instant_bookable                              13984 non-null  object
 46  calculated_host_listings_count                13984 non-null  int64
 47  calculated_host_listings_count_entire_homes   13984 non-null  int64
 48  calculated_host_listings_count_private_rooms  13984 non-null  int64
 49  calculated_host_listings_count_shared_rooms   13984 non-null  int64
 50  reviews_per_month                             10706 non-null  float64
dtypes: float64(18), int64(21), object(12)
memory usage: 5.4+ MB

***PARTE DOS***

In [4]:
#review_scores_value Y super host
filtroA=berlin_data[(berlin_data["review_scores_value"] >= 3) & (berlin_data["host_is_superhost"]=="t")]
print(filtroA)
filtroA.to_csv("scores_SH.csv")

       Unnamed: 0                   id       scrape_id  \
2               2  1205255838613758737  20241221052002
5               5   886772024913265656  20241221052002
6               6             13761071  20241221052002
10             10              1697691  20241221052002
11             11  1004454780293034887  20241221052002
...           ...                  ...             ...
13771       13771             47486110  20241221052002
13785       13785   909320248591901398  20241221052002
13803       13803  1130292978164168626  20241221052002
13807       13807  1072891616519112883  20241221052002
13979       13979  1066742710842868324  20241221052002

                                                   name  \
2        Luxurous game room with private bath in X-Berg
5                         Studio in the heart of Berlin
6      Central flat near Alex with fiber optic Internet
10           Charming flat w.Balcony | Perfect location
11      Large room in city centre with private bathroom
...                                                 ...
13771                      Big happy room in Schöneberg
13785   Beautiful Kreuzberg apartment, 2 min from canal
13803                                      Berlin Mitte
13807                       Well located Room in Berlin
13979                   Cozy bedroom in a stylish house

                                             description  ...  \
2      Cozy private room in Berlin Mitte with private...  ...
5      Located in the heart of Berlin, this stylish a...  ...
6      This light and clean apartment is located in a...  ...
10     A cosy and quiet 2-room flat in a perfect loca...  ...
11     - Spacious and quiet room (28 m², 300 sq ft)<b...  ...
...                                                  ...  ...
13771  40 m2 room in the centre of Schöneberg! <br />...  ...
13785  I am inviting you to experience comfort and ch...  ...
13803  Enjoy easy access to everything from this perf...  ...
13807  From this centrally located accommodation, you...  ...
13979                                                NaN  ...

       calculated_host_listings_count  \
2                                   1
5                                  21
6                                   2
10                                  1
11                                  1
...                               ...
13771                               2
13785                               1
13803                               2
13807                               1
13979                               3

      calculated_host_listings_count_entire_homes  \
2                                               0
5                                              21
6                                               2
10                                              1
11                                              0
...                                           ...
13771                                           1
13785                                           1
13803                                           0
13807                                           0
13979                                           0

      calculated_host_listings_count_private_rooms  \
2                                                1
5                                                0
6                                                0
10                                               0
11                                               1
...                                            ...
13771                                            1
13785                                            0
13803                                            2
13807                                            1
13979                                            3

       calculated_host_listings_count_shared_rooms  reviews_per_month
2                                                0               9.53
5                                                0               0.13
6                                                0               3.49
10                                               0               0.56
11                                               0               2.81
...                                            ...                ...
13771                                            0               0.02
13785                                            0               1.27
13803                                            0               2.35
13807                                            0               3.50
13979                                            0               0.82

[2932 rows x 51 columns]

In [5]:
#propiedades que no tienen un baño
filtroB = berlin_data[berlin_data["bathrooms"] != 1] 
print(filtroB)
filtroB.to_csv("bathromms.csv")

       Unnamed: 0                   id       scrape_id  \
0               0              2084992  20241221052002
1               1  1123383729460847373  20241221052002
3               3              8164759  20241221052002
4               4             18836877  20241221052002
7               7             16141397  20241221052002
...           ...                  ...             ...
13977       13977  1036900333763076342  20241221052002
13978       13978  1054860335519325938  20241221052002
13979       13979  1066742710842868324  20241221052002
13981       13981  1172288594718636022  20241221052002
13982       13982  1233927040956879330  20241221052002

                                                    name  \
0       Nice and cozy apartment in Kreuzberg, Graefekiez
1      Furnished room in well equipped serviced apart...
3                           Beautiful single-room studio
4                           Unterkunft zentral in Berlin
7                         Ein Raum Wohnung in Schöneberg
...                                                  ...
13977                          Spacious Loft in Neukölln
13978                                 Apartment in mitte
13979                    Cozy bedroom in a stylish house
13981                         Deluxe Superior Accessible
13982                              Prenzlauerberg Berlin

                                             description  ...  \
0      Our cosy two room Apartment (70qm) in a vibrat...  ...
1      Room in an apartment available. Apartment has ...  ...
3      Experience the “real Berlin” in our small and ...  ...
4      The accommodation has 3 rooms, however, is onl...  ...
7      My place is close to the Odeon cinema, Lidl an...  ...
...                                                  ...  ...
13977                                                NaN  ...
13978  Located in the heart of Berlin! 10 minutes wal...  ...
13979                                                NaN  ...
13981  This wheelchair accessible double room feature...  ...
13982  Fully equipped apartment with large balcony in...  ...

       calculated_host_listings_count  \
0                                   1
1                                   3
3                                   1
4                                   1
7                                   1
...                               ...
13977                               1
13978                               1
13979                               3
13981                               6
13982                               2

      calculated_host_listings_count_entire_homes  \
0                                               1
1                                               1
3                                               1
4                                               1
7                                               1
...                                           ...
13977                                           1
13978                                           1
13979                                           0
13981                                           0
13982                                           2

      calculated_host_listings_count_private_rooms  \
0                                                0
1                                                2
3                                                0
4                                                0
7                                                0
...                                            ...
13977                                            0
13978                                            0
13979                                            3
13981                                            6
13982                                            0

       calculated_host_listings_count_shared_rooms  reviews_per_month
0                                                0               0.09
1                                                0                NaN
3                                                0               0.01
4                                                0                NaN
7                                                0                NaN
...                                            ...                ...
13977                                            0                NaN
13978                                            0               0.18
13979                                            0               0.82
13981                                            0                NaN
13982                                            0                NaN

[6613 rows x 51 columns]

In [6]:
#precio entre 100 y 200
filtroC = berlin_data.loc[(berlin_data["price"] >= "$100") & (berlin_data["price"] <= "$200")]  
filtroC
filtroC.to_csv("entre100_200.csv")

In [7]:
#instant_bookable y host_indetity_verified 
filtroD=berlin_data[(berlin_data["host_identity_verified"] =="f") & (berlin_data["instant_bookable"]=="t")]
print(filtroD)
filtroD.to_csv("bookable_indetity.csv")

       Unnamed: 0                   id       scrape_id  \
93             93   535415314007589795  20241221052002
254           254  1218266990175103164  20241221052002
299           299  1249106973521025839  20241221052002
419           419   898530900032595096  20241221052002
533           533             33471700  20241221052002
...           ...                  ...             ...
13739       13739   668084400412557430  20241221052002
13759       13759   812260888750485821  20241221052002
13874       13874             18066365  20241221052002
13921       13921             38566942  20241221052002
13926       13926             38893531  20241221052002

                                                    name  \
93                       Great Apartment close to Kudamm
254                      Helle, verkehrsgünstige Wohnung
299                       Moderne, helle Oase mit Balkon
419      Cosy Single Room, Central spot in Mitte, Berlin
533                                 We love you & Berlin
...                                                  ...
13739                                    Casa Monteverde
13759                          Modernes Altbau-Apartment
13874                    Stunning Alt-Bau Room in Berlin
13921       Gemütliche Wohnung im Herzen Friedrichshains
13926  Schönes Privatzimmer im Herzen von Friedrichshain

                                             description  ...  \
93     Enjoy freedom and flexibility. Homaris apartme...  ...
254    Centrally located in Steglitz, close to shoppi...  ...
299    Welcome to your perfect getaway! You will love...  ...
419    This room has everything you need to live, wor...  ...
533    Hello dear travelers,<br />your next destinati...  ...
...                                                  ...  ...
13739  The apartment is located on the beautiful peni...  ...
13759  Enjoy a stylish experience at this centrally-l...  ...
13874  Beautifully decorated, well lit room.<br />1 m...  ...
13921  Small quiet apartment in the backyard.<br />We...  ...
13926  The room has a bed (1.40×2m) and is minimalist...  ...

       calculated_host_listings_count  \
93                                  3
254                                 1
299                                 1
419                                 6
533                                 1
...                               ...
13739                               1
13759                               1
13874                               1
13921                               1
13926                               1

      calculated_host_listings_count_entire_homes  \
93                                              3
254                                             1
299                                             1
419                                             6
533                                             1
...                                           ...
13739                                           0
13759                                           1
13874                                           0
13921                                           1
13926                                           0

      calculated_host_listings_count_private_rooms  \
93                                               0
254                                              0
299                                              0
419                                              0
533                                              0
...                                            ...
13739                                            1
13759                                            0
13874                                            1
13921                                            0
13926                                            1

       calculated_host_listings_count_shared_rooms  reviews_per_month
93                                               0               2.60
254                                              0               1.43
299                                              0               1.10
419                                              0               0.81
533                                              0               0.19
...                                            ...                ...
13739                                            0                NaN
13759                                            0                NaN
13874                                            0               0.05
13921                                            0               0.06
13926                                            0                NaN

[160 rows x 51 columns]

In [8]:
#hotel room o  Private room 
filtroE = berlin_data[(berlin_data["room_type"] =="Hotel room") | (berlin_data["room_type"]=="Private room")]
print(filtroE)
filtroE.to_csv("Hotelroom_private.csv")

       Unnamed: 0                   id       scrape_id  \
1               1  1123383729460847373  20241221052002
2               2  1205255838613758737  20241221052002
11             11  1004454780293034887  20241221052002
12             12             15245252  20241221052002
14             14             32116312  20241221052002
...           ...                  ...             ...
13972       13972             27868394  20241221052002
13974       13974             37747234  20241221052002
13976       13976             38070271  20241221052002
13979       13979  1066742710842868324  20241221052002
13981       13981  1172288594718636022  20241221052002

                                                    name  \
1      Furnished room in well equipped serviced apart...
2         Luxurous game room with private bath in X-Berg
11       Large room in city centre with private bathroom
12                     Cosy and bright room for 3 People
14        Misty Forest Hotel-Apartment in Friedrichshain
...                                                  ...
13972                        nice room in Friedrichshain
13974  Beautiful Big Bright Room in Kreuzberg / Neukolln
13976                   Zauberhaftes Zimmer in Kreuzberg
13979                    Cozy bedroom in a stylish house
13981                         Deluxe Superior Accessible

                                             description  ...  \
1      Room in an apartment available. Apartment has ...  ...
2      Cozy private room in Berlin Mitte with private...  ...
11     - Spacious and quiet room (28 m², 300 sq ft)<b...  ...
12     My place is close to Frankfurt's avenue. Vario...  ...
14     Located in the heart of Friedrichshain - one o...  ...
...                                                  ...  ...
13972  Hello,<br /><br />offer a nice bright room her...  ...
13974  Spacious, bright room filled with plants. Apar...  ...
13976  We are currently a 2 shared apartment and curr...  ...
13979                                                NaN  ...
13981  This wheelchair accessible double room feature...  ...

       calculated_host_listings_count  \
1                                   3
2                                   1
11                                  1
12                                  1
14                                  7
...                               ...
13972                               1
13974                               2
13976                               1
13979                               3
13981                               6

      calculated_host_listings_count_entire_homes  \
1                                               1
2                                               0
11                                              0
12                                              0
14                                              6
...                                           ...
13972                                           0
13974                                           0
13976                                           0
13979                                           0
13981                                           0

      calculated_host_listings_count_private_rooms  \
1                                                2
2                                                1
11                                               1
12                                               1
14                                               0
...                                            ...
13972                                            1
13974                                            2
13976                                            1
13979                                            3
13981                                            6

       calculated_host_listings_count_shared_rooms  reviews_per_month
1                                                0                NaN
2                                                0               9.53
11                                               0               2.81
12                                               0               0.01
14                                               0               1.66
...                                            ...                ...
13972                                            0               0.12
13974                                            0                NaN
13976                                            0               0.06
13979                                            0               0.82
13981                                            0                NaN

[4423 rows x 51 columns]

In [9]:
#mas de 4 accomadtes
filtroF = berlin_data[berlin_data["accommodates"]>4] 
print(filtroF)
filtroF.to_csv("accomodates.csv")

       Unnamed: 0                  id       scrape_id  \
6               6            13761071  20241221052002
19             19            43466772  20241221052002
29             29  568524485826835987  20241221052002
33             33  939185728575965294  20241221052002
50             50            21038831  20241221052002
...           ...                 ...             ...
13772       13772  966776100771363947  20241221052002
13853       13853             3945778  20241221052002
13923       13923            29173722  20241221052002
13949       13949            42059333  20241221052002
13959       13959            43661152  20241221052002

                                                    name  \
6       Central flat near Alex with fiber optic Internet
19              Myhappyplace two in the middle of Berlin
29         Numa | Large 1-Bedroom Apartment with Sofabed
33                          Space + Hygge feeling 130 qm
50     Vintage Vibes: Spacious 4-Room Apartment in Mitte
...                                                  ...
13772                                   luxury Apartment
13853                   120qm Altbau in Berlin Friedenau
13923        Big cozy apartment in the heart of Neukölln
13949                                     Cuba apartment
13959     Sunny roof top apartment in Berlin Lichtenberg

                                             description  ...  \
6      This light and clean apartment is located in a...  ...
19     The location of the accommodation in Berlin-Mi...  ...
29     The 61-square-meter, freshly renovated apartme...  ...
33     We are hosting 8 Apartments in a house in Berl...  ...
50     Escape the city bustle and experience the quie...  ...
...                                                  ...  ...
13772  The apartment itself comes fully furnished wit...  ...
13853  Spacious old building apartment on the border ...  ...
13923  Cozy flat with two big rooms, balkony, bathroo...  ...
13949  Nice furnished apartment on the second floor (...  ...
13959  Our apartment is approx. 140m2 big and located...  ...

       calculated_host_listings_count  \
6                                   2
19                                  2
29                                  7
33                                  6
50                                 21
...                               ...
13772                               1
13853                               1
13923                               1
13949                              21
13959                               1

      calculated_host_listings_count_entire_homes  \
6                                               2
19                                              2
29                                              7
33                                              6
50                                             21
...                                           ...
13772                                           1
13853                                           1
13923                                           1
13949                                          21
13959                                           1

      calculated_host_listings_count_private_rooms  \
6                                                0
19                                               0
29                                               0
33                                               0
50                                               0
...                                            ...
13772                                            0
13853                                            0
13923                                            0
13949                                            0
13959                                            0

       calculated_host_listings_count_shared_rooms  reviews_per_month
6                                                0               3.49
19                                               0               1.32
29                                               0               1.26
33                                               0               0.29
50                                               0               0.05
...                                            ...                ...
13772                                            0                NaN
13853                                            0               0.10
13923                                            0                NaN
13949                                            0                NaN
13959                                            0               0.09

[1934 rows x 51 columns]